=== mihailovasiljevic/XML2016/data/amandman.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/amandman"
    xmlns:ama="http://www.ftn.uns.ac.rs/amandman" xmlns:akt="http://www.ftn.uns.ac.rs/pravniAkt">
    <xs:import namespace="http://www.ftn.uns.ac.rs/pravniAkt" schemaLocation="akt.xsd"/>
    <xs:element name="Amandman">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="oznaka" type="xs:int"/>
                 <xs:element name="vremeFormiranja" type="xs:string"/>
               	<xs:element name="redniBroj" type="xs:string"/>
                <xs:element name="zaglavlje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element default="РЕПУБЛИКА СРБИЈА" name="drzava" type="xs:string"/>
                            <xs:element default="НАРОДНА СКУПШТИНА" name="organ" type="xs:string"/>
                            <xs:element name="predlagac" type="xs:string"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="datum" type="xs:date"/>
                            <xs:element name="mesto" type="xs:string"/>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uvod">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element default="ПРЕДСЕДНИКУ НАРОДНЕ СКУПШТИНЕ" name="naslov"
                                type="xs:string"/>
                            <xs:sequence>
                                <xs:choice>
                                    <xs:element name="tekst" type="xs:string"/>
                                    <xs:element name="akt" type="ama:akt"/>
                                </xs:choice>
                            </xs:sequence>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="glavniDeo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element default="АМАНДМАН" name="naslov" type="xs:string"/>
                            <xs:element name="sadrzaj">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="tekst">
                                            <xs:complexType mixed="true">
                                                <xs:sequence maxOccurs="1">
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element name="clan">
                                                  <xs:complexType mixed="true">
                                                  <xs:attribute name="href" type="xs:anyURI"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="1" name="stav">
                                                  <xs:complexType mixed="true">
                                                  <xs:attribute name="href" type="xs:anyURI"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="1" name="tacka">
                                                  <xs:complexType mixed="true">
                                                  <xs:attribute name="href" type="xs:anyURI"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="podtacka">
                                                  <xs:complexType mixed="true">
                                                  <xs:attribute name="href" type="xs:anyURI"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:choice>
                                                  <xs:element name="operacija" maxOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="menjaSe"/>
                                                  <xs:enumeration value="dopunjujeSe"/>
                                                  <xs:enumeration value="briseSe"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="obrazlozenje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naslov" type="xs:string"/>
                            <xs:element name="tekst" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="potpis">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funkcija" type="xs:string"/>
                            <xs:element name="imeIPrezime" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="PK">
            <xs:selector xpath="ama:Amandman"/>
            <xs:field xpath="ama:Amandman/ama:oznaka"/>
        </xs:key>
    </xs:element>
    <xs:complexType mixed="true" name="akt">
        <xs:attribute name="href" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== mihailovasiljevic/XML2016/data/amandman2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ama:Amandman xmlns:ama="http://www.ftn.uns.ac.rs/amandman" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/amandman amandman.xsd ">
  <ama:oznaka>0</ama:oznaka>
  <ama:vremeFormiranja>ama:vremeFormiranja</ama:vremeFormiranja>
  <ama:redniBroj>ama:redniBroj</ama:redniBroj>
  <ama:zaglavlje>
    <ama:drzava>РЕПУБЛИКА СРБИЈА</ama:drzava>
    <ama:organ>НАРОДНА СКУПШТИНА</ama:organ>
    <ama:predlagac>ama:predlagac</ama:predlagac>
    <ama:mesto>ama:mesto</ama:mesto>
  </ama:zaglavlje>
  <ama:uvod>
    <ama:naslov>ПРЕДСЕДНИКУ НАРОДНЕ СКУПШТИНЕ</ama:naslov>
    <ama:tekst>ama:tekst</ama:tekst>
  </ama:uvod>
  <ama:glavniDeo>
    <ama:naslov>АМАНДМАН</ama:naslov>
    <ama:sadrzaj>
      <ama:tekst>
        <ama:clan/>
        <ama:operacija>menjaSe</ama:operacija>
      </ama:tekst>
    </ama:sadrzaj>
  </ama:glavniDeo>
  <ama:obrazlozenje>
    <ama:naslov>ama:naslov</ama:naslov>
    <ama:tekst>ama:tekst</ama:tekst>
  </ama:obrazlozenje>
  <ama:potpis>
    <ama:funkcija>ama:funkcija</ama:funkcija>
    <ama:imeIPrezime>ama:imeIPrezime</ama:imeIPrezime>
  </ama:potpis>
</ama:Amandman>

=== mihailovasiljevic/XML2016/data/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ama:Amandman xmlns:akt="http://www.ftn.uns.ac.rs/pravniAkt"
 xmlns:ama="http://www.ftn.uns.ac.rs/amandman"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/amandman file:/F:/Projects/XML/pinf_xws_docs/xml/schema/amandman.xsd">
    <ama:oznaka>0</ama:oznaka>
    <ama:zaglavlje>
        <ama:drzava>РЕПУБЛИКА СРБИЈА</ama:drzava>
        <ama:organ>НАРОДНА СКУПШТИНА</ama:organ>
        <ama:predlagac>predlagac0</ama:predlagac>
        <ama:mesto>mesto0</ama:mesto>
    </ama:zaglavlje>
    <ama:uvod>
        <ama:naslov>ПРЕДСЕДНИКУ НАРОДНЕ СКУПШТИНЕ</ama:naslov>
        <ama:tekst>tekst0</ama:tekst>
    </ama:uvod>
    <ama:glavniDeo>
        <ama:naslov>АМАНДМАН</ama:naslov>
        <ama:sadrzaj>
            <ama:tekst>Iz stava <ama:stav>13</ama:stav> reci "ama" 
                <ama:operacija>menjaSe</ama:operacija> recima "pera"
            </ama:tekst>
            <ama:tekst>
                <ama:stav>
                </ama:stav>
                <ama:clan>
                </ama:clan>
                <ama:operacija>menjaSe</ama:operacija>
            </ama:tekst>
        </ama:sadrzaj>
    </ama:glavniDeo>
    <ama:obrazlozenje>
        <ama:naslov>naslov0</ama:naslov>
        <ama:tekst>tekst1</ama:tekst>
    </ama:obrazlozenje>
    <ama:potpis>
        <ama:funkcija>funkcija0</ama:funkcija>
        <ama:imeIPrezime>imeIPrezime0</ama:imeIPrezime>
    </ama:potpis>
</ama:Amandman>
